version: "3.9"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_delivery
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  keycloak_delivery:
    container_name: keycloak_delivery
    image: jboss/keycloak:15.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"