version: "3.9"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_delivery
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  keycloak_delivery:
    container_name: keycloak_delivery
    image: jboss/keycloak:15.0.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  jaeger_delivery:
    container_name: jaeger_delivery
    image: jaegertracing/all-in-one:1.26
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"